### ISSUE TITLE
What do you mean by unstable?

### ISSUE THREAD

**Issue by jorge-graca-sky** [ahoendgen/ts-transformer-preval#8]
Hi!

I have been searching for a TS preval for a while now, and I finally found this one! This is exactly what I wanted, but why do you say it is unstable?

Does it not have some feature you would like? Does it work reasonably well?

I will try it out when I get a change though, thanks :)

**Comment by ahoendgen** [comment]
Hi
i consider it unstable because there are no tests and i don't actively maintain it.
It was built exactly for the reason you mention, i also needed it but didn't find preval for TS, only for JS.
So far it worked good for me, no problems but it's the classic "it works on my machine" (or in this case "it works in my build pipeline" :D )

Greetings,
André
